### ISSUE TITLE
i18n support of simple chinese

### ISSUE THREAD

**Issue by yige-yigeren** [seuyh/stellaris-dlc-unlocker#6]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
More language support, like Simple Chinese.

**Describe alternatives you've considered**
I can help translate a /design/languages/zh_cn.txt
If you need it, I also can help to installer_zh_cn.py.

**Additional context**
I can help translate into Chinese, but I want to ask you first if you are willing to support

**Comment by seuyh** [comment]
At the moment, the translation files do not contain all the text that the program uses, some text is written directly in the program itself, because of this it is not so easy at the moment, but in the future I will add the possibility of a complete translation by adding only one file. Thank you for the offer.

**Comment by seuyh** [comment]
released
